name: "Build container"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.1.0
        
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          platforms: linux/amd64
